name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup bats
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.6.0
          
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test
